import React, { useState } from 'react';
import { Plus, Minus, Info } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

const faqs = [
  {
    question: "1. How does AI-powered marketing specifically help my medical practice grow?",
    answer: "Unlike traditional marketing, our AI-driven approach analyzes real-time patient behavior and search patterns to predict which individuals in your local area are actively seeking your specific specialty. By combining this data with human creative strategy, we ensure your practice appears in front of the right patient at the precise moment they are ready to book an appointment, significantly lowering your cost-per-acquisition."
  },
  {
    question: "2. Is your digital marketing strategy HIPAA-compliant?",
    answer: "Absolutely. Patient privacy is our top priority. We ensure that all lead generation forms, tracking pixels, and email marketing automation tools are fully HIPAA-compliant. We never store Sensitive Health Information (SHI) on non-secure servers and use encrypted methods to transfer patient inquiries directly to your practice management system."
  },
  {
    question: "3. How do you target \"high-intent\" patients instead of just driving general traffic?",
    answer: "We don’t just look for \"visitors\"; we look for patients. By utilizing advanced Local SEO and intent-based PPC (Pay-Per-Click), we target keywords that indicate a need for immediate care, such as \"specialist near me\" or \"emergency [specialty] treatment.\" This ensures your budget is spent on individuals who are ready to schedule, rather than those just performing general health research."
  },
  {
    question: "4. How do you help manage my practice’s online reputation and reviews?",
    answer: "In medicine, trust is everything. We implement automated systems that encourage your satisfied patients to leave positive reviews on Google, Healthgrades, and Vitals. Simultaneously, we monitor for any negative feedback, alerting your team immediately so you can address concerns professionally and maintain a 4.5+ star rating that builds instant patient confidence."
  },
  {
    question: "5. Which social media platforms are most effective for doctors?",
    answer: "For medical practices, we typically find the highest engagement on Instagram and Facebook for patient education and community building, while LinkedIn is used for professional referrals and authority building. We create a bespoke mix of \"Behind-the-Scenes\" content, patient success stories, and health tips to humanize your practice and stay top-of-mind."
  },
  {
    question: "6. Can I track the exact Return on Investment (ROI) from my marketing spend?",
    answer: "Yes. Our \"Growth Dashboard\" provides 24/7 transparency into your campaign performance. You can see exactly how many phone calls, form submissions, and booked appointments were generated by each marketing channel. We focus on \"Patient Lifetime Value\" to ensure your marketing is a profitable investment, not an expense."
  },
  {
    question: "7. How much time will my medical staff need to commit to marketing efforts?",
    answer: "We know your primary focus is patient care. Our team acts as an extension of your practice; we handle the content creation, ad management, and technical SEO. Your involvement is limited to a brief monthly strategy review and approving the content calendar, ensuring your digital presence grows without adding to your staff's clinical workload."
  },
  {
    question: "8. How do you establish me as a \"Thought Leader\" in my medical specialty?",
    answer: "We utilize high-authority content marketing, including video snippets of you answering common patient questions and long-form educational blogs. This not only improves your SEO rankings but also positions you as the leading expert in your field, making patients feel they already know and trust you before they ever walk through your door."
  },
  {
    question: "9. What makes SEG’s approach different from traditional healthcare marketing firms?",
    answer: "Traditional firms often rely on \"set it and forget it\" templates. We use a proprietary blend of AI-driven data analysis and human creative storytelling. We don't just buy ads; we build a localized ecosystem that makes your practice the \"obvious choice\" in your community through a dominant omnichannel presence."
  },
  {
    question: "10. How long does it take to see a measurable increase in new patient appointments?",
    answer: "While SEO is a long-term authority-building strategy (3-6 months), our AI-optimized PPC and Social Ads can begin driving new patient inquiries within the first 14 to 30 days. We aim for a \"quick win\" phase to boost your patient volume immediately while simultaneously building the organic foundation for sustained, long-term growth."
  }
];

const FAQ: React.FC = () => {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  return (
    <section id="faq" className="py-20 md:py-24 bg-white overflow-hidden">
      <div className="max-w-7xl mx-auto px-6 lg:px-12">
        <div className="grid lg:grid-cols-[1fr,1.5fr] gap-6 lg:gap-20 items-center">
          
          {/* Left: Header */}
          <div className="lg:sticky lg:top-32 text-center lg:text-left">
            <motion.div
                initial={{ opacity: 0, x: -20 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
            >
                <h3 className="text-4xl md:text-5xl font-bold text-[#144272] mb-0 lg:mb-6 leading-tight font-outfit">
                  Frequently <br className="hidden lg:block" />Asked Questions
                </h3>
            </motion.div>
          </div>

          {/* Right: Modern Accordion */}
          <div className="space-y-2">
            {faqs.map((faq, index) => (
              <motion.div 
                key={index} 
                initial={{ opacity: 0, y: 15 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                className={`rounded-2xl transition-all duration-300 ${openIndex === index ? 'bg-[#EBF4F8]' : 'bg-[#F5F9FB]'}`}
              >
                <button
                  onClick={() => setOpenIndex(openIndex === index ? null : index)}
                  className="w-full flex items-center justify-between gap-4 p-6 text-left focus:outline-none"
                >
                  <span className={`text-xl font-bold transition-colors font-outfit ${openIndex === index ? 'text-brand-healist-charcoal' : 'text-gray-600'}`}>
                    {faq.question}
                  </span>
                  <div className={`shrink-0 transition-transform duration-300 ${openIndex === index ? 'rotate-180' : ''}`}>
                    <Plus className={`h-5 w-5 ${openIndex === index ? 'text-brand-healist-charcoal' : 'text-gray-400'}`} />
                  </div>
                </button>
                
                <AnimatePresence>
                  {openIndex === index && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: "auto", opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.3, ease: "easeOut" }}
                    >
                      <div className="px-6 pb-6 text-gray-500 text-lg font-medium leading-relaxed font-outfit">
                        {faq.answer}
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </motion.div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
};

export default FAQ;
